### ISSUE TITLE
Indirect upgrade from v3->v6core

### ISSUE THREAD

**Issue by james3126** [rconfig/rconfig#105]
Hi,

Is there any workable method to upgrade an old v3 install to v6 core? I see it's already noted on the rConfig website that there's no direct upgrade from v3 to v6. But is there any workable method to 'indirectly' upgrade via manually tweaking or transplanting data, etc..? 

I'd like to upgrade my little instance but I think it's going to leave me without any config history. Not the end of the world, but would be nice if possible :)

**Comment by stephenstack** [comment]
HI, i am sorry for the delay, but we have been quite busy with the release of V7. We have a tool, called rConfig-shift, which may help, but the setup and implementation is a bit technical, and only internally document. It should work with 6, but TBH, its been a long time since we tried it. https://github.com/rconfig/rConfig-Shift
Contact info@rconfig.com for assistance if you still need it
