### ISSUE TITLE
Getting PHP Error when trying to log into RConfig V4

### ISSUE THREAD

**Issue by pbmorse** [rconfig/rconfig#24]
Hello,

I followed the rConfig tutorial updating from V3.5 to V4 in Cent OS7. Everything worked good on installing but when it went to https://192.168.XXX.XXX/install to my rConfig, I went through the rConfig Pre Installation check list again, installing a new database, verifying settings etc. On the last section where it has the Final Check button. When I click on the button, nothing happens. Doesn't show anything of what has passed or if anything has any errors. The address shows https://192.168.xxx.xxx/install/finalcheck.php#javascript:void(0);  
When i try to log into rConfig i get a response from my browser that the page isnt working.

**Comment by rconfig** [comment]
you will need to use debugging tools to see why this issue is occuring. F12 for JS debugging on your browser and PHP logging for PHP script errors. This usually happens when you have not followed all steps correctly, or there is an error in the installation. you can review the /home/install.log for errors. Make sure all fields are completed for the setup and ensure you have run the 'chown -R apache /home/rconfig/' command on the server
