### ISSUE TITLE
PHP Fatal error:  Can't use method return value in write context in /home/rconfig/classes/connection2.class.php on line 111

### ISSUE THREAD

**Issue by vipp** [rconfig/rconfig#70]
When trying to do a manual download using php /home/rconfig/lib/showCmdScript.php 894503 I am getting the below error. Any help would be greatly appreciated. 

PHP Fatal error:  Can't use method return value in write context in /home/rconfig/classes/connection2.class.php on line 111

This is a fresh install on a fresh deployment of Centos 7.

**Comment by rconfig** [comment]
Hi,

Your issue is likely to be either;
1.	A credential issue
2.	A prompt configuration issue (has the correct device prompt been placed on the device config page in rConfig)
3.	Or other connectivity issue. KB2001 on the knowledge base @rconfig.com can help assist you.
4.	Please read help files and support documentation.

I do not provide direct support unless you pay for support. Sorry, but otherwise I could not eat 😊

Regards
