### ISSUE TITLE
Not able to fetch nor download configuration

### ISSUE THREAD

**Issue by mmihir82** [rconfig/rconfig#71]
Hello,
I have finished installation. I have added device. But some how I am not able to "manual download" the configuration nor send the snippets. I have also schedule a fetch configuration, that didn't work either. Can you please help, where I should look? From the same service, I was able to ssh to the switch and login successful, but not able to from rConfig.
Please point me to correct direction.

**Comment by rconfig** [comment]
Hi
 
Your issue is likely to be either;
A credential issue
A prompt configuration issue (has the correct device prompt been placed on the device config page in rConfig)
Or other connectivity issue. KB2001 on the knowledge base @rconfig.com can help assist you.
Please read help files and support documentation.
 
I do not provide direct support unless you pay for support. Sorry, but otherwise I could not eat 😊
 
Regards
